server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///springboot-vue
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.example: debug