server:
#  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///springboot-vue?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.example: debug